export const RECOMMENDATIONS_REQUEST = 'common/RECOMMENDATIONS_REQUEST';
export const RECOMMENDATIONS_RECEIVED = 'common/RECOMMENDATIONS_RECEIVED';
export const RECOMMENDATIONS_ERROR = 'common/RECOMMENDATIONS_ERROR';
